### ISSUE TITLE
Download link was not valid

### ISSUE THREAD

**Issue by LiuYunjia** [WashU-BG/nssi_gwas#1]
Hello,
Thanks for sharing this gwas resutls, but the link was not valid. 
I would be grateful if you update this link for download.

**Comment by sarahcolbert** [comment]
Hi!
The link was accidentally set to be disabled after a few months, but I've just turned that feature off so you should be able to access the download from the link in the README. If you still are unable to, please reopen the issue and let me know. Thanks for bringing this to our attention! 
- Sarah
